name: Prod Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and build
        run: |
          npm i
          npm run build

      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: '.,!node_modules'
          target: '~/dev/fiatvoluntastua'
          overwrite: true
          rm: true
          timeout: 300s

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cp -a ~/backup/fiatvoluntastua/. ~/dev/fiatvoluntastua 
            cd ~/dev/fiatvoluntastua
            npm run docker:stop
            npm run docker:build
            npm run docker:start
